name: test-publish-private-docker-image.yml
on:
  workflow_dispatch:
    inputs:
      image-registry:
        default: ghcr.io
        description: Image registry
        required: true
      image-name:
        description: Image name
        default: gmzwinge/gmzwinge-test-private-docker-image
        required: true
      image-version:
        description: Image tag like '1.0'
        default: 1.0.0
        required: true
permissions:
  packages: write
jobs:
  test-publish-private-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Login Docker to be able to pull images, including private images:
      #- run: echo '${{ secrets.PRIVATE_PACKAGES_READ }}' | docker login '${{ inputs.image-registry }}' -u '${{ github.actor }}' --password-stdin
      - run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login '${{ inputs.image-registry }}' -u '${{ github.actor }}' --password-stdin
      # Create a simple Docker file:
      - run: |
          cat << EOF > Dockerfile
            # A public image from Docker hub:
            FROM alpine:3.19
            # Ensure the layer is different at every build by having a different command and file created
            # at every Docker build, eg a command that displays a nanoseconds date time stamp.
            # Not sure if both command and file created are required.
            WORKDIR /app
            RUN echo "$(date +%s%N)" > "$(date +%s%N)"
          EOF
      - run: docker build --tag '${{ inputs.image-registry }}/${{ inputs.image-name }}:${{ inputs.image-version }}' --file Dockerfile .
      - run: docker push '${{ inputs.image-registry }}/${{ inputs.image-name }}:${{ inputs.image-version }}'
